'use strict';
// One-line node setup, like Pterodactyl's auto-deploy:
//
//   curl -fsSL https://panel/node-deploy/<code> | sudo bash
//
// An admin generates the code on the node's Configuration tab. It works once and expires after
// 15 minutes. Using it issues the node a fresh permanent token, which the script writes into the
// node's config.yml. The agent bundle is then downloaded from the panel using that token.
const express = require('express');
const fs = require('fs');
const path = require('path');
const { spawn } = require('child_process');
const { db, audit } = require('../db');
const nodes = require('../services/nodes');
const { sha256, randomToken } = require('../util');

const router = express.Router();
const ROOT = path.join(__dirname, '..', '..');
const BUNDLE = ['package.json', 'package-lock.json', 'src', 'install-node.sh', 'kvmpanel-node.service'];
const HOST_RE = /^[A-Za-z0-9.\-:[\]]{1,255}$/;
const text = (res, status, body) => res.status(status).type('text/plain').send(body);

const shq = (s) => `'${String(s).replace(/'/g, `'\\''`)}'`; // single-quote for bash

function installScript({ url, token, name }) {
  return `#!/usr/bin/env bash
# Diablo node installer for ${JSON.stringify(name)}. Generated by the panel. The token below is private.
set -Eeuo pipefail

main() {
  PANEL_URL=${shq(url)}
  NODE_TOKEN=${shq(token)}

  say() { printf '\\n\\033[1;36m==>\\033[0m %s\\n' "$*"; }
  die() { printf '\\033[1;31mError:\\033[0m %s\\n' "$*" >&2; exit 1; }

  [[ $EUID -eq 0 ]] || die "Run this as root, for example: curl -fsSL <link> | sudo bash"
  command -v apt-get >/dev/null || die "This installer supports Debian and Ubuntu (apt)."

  say "Preparing"
  export DEBIAN_FRONTEND=noninteractive
  apt-get update -y
  apt-get install -y --no-install-recommends curl ca-certificates tar

  tmp=$(mktemp -d)
  trap 'rm -rf "$tmp"' EXIT

  say "Downloading the node agent from $PANEL_URL"
  curl -fsSL -H "Authorization: Bearer $NODE_TOKEN" "$PANEL_URL/node-bundle.tgz" | tar xz -C "$tmp"

  cd "$tmp"
  bash ./install-node.sh --panel "$PANEL_URL" --token "$NODE_TOKEN"
}

# Everything is defined before it runs, and stdin is detached, so nothing inside can swallow the rest of the script.
main "$@" </dev/null
`;
}

router.get('/node-deploy/:code', (req, res) => {
  const code = String(req.params.code || '');
  const node = /^[a-f0-9]{32}$/.test(code)
    && db.prepare('SELECT * FROM nodes WHERE deploy_hash = ? AND id != 1 AND deploy_expires > ?').get(sha256(code), Date.now());
  if (!node) return text(res, 404, 'echo "This deploy link is invalid, expired or already used. Generate a new one on the node\'s Configuration tab." >&2; exit 1\n');
  const host = req.get('host') || '';
  if (!HOST_RE.test(host)) return text(res, 400, 'echo "Bad Host header" >&2; exit 1\n');

  const token = `knode_${randomToken(24)}`;
  db.prepare('UPDATE nodes SET token_hash = ?, deploy_hash = NULL, deploy_expires = NULL WHERE id = ?').run(sha256(token), node.id);
  nodes.disconnect(node.id); // an old agent with the previous token stops working
  audit(null, 'node.deploy', node.name);
  text(res, 200, installScript({ url: `${req.protocol}://${host}`, token, name: node.name }));
});

// The agent files, as a tar.gz. Protected by the node's own token.
router.get('/node-bundle.tgz', (req, res) => {
  const h = req.get('authorization') || '';
  const token = h.startsWith('Bearer ') ? h.slice(7).trim() : '';
  const node = token && db.prepare('SELECT id FROM nodes WHERE token_hash = ? AND id != 1').get(sha256(token));
  if (!node) return setTimeout(() => text(res, 401, 'Unauthorized\n'), 400);
  const missing = BUNDLE.filter((f) => !fs.existsSync(path.join(ROOT, f)));
  if (missing.length) return text(res, 500, `This panel installation is missing ${missing.join(', ')}. Reinstall the panel from the latest package.\n`);
  res.set({ 'Content-Type': 'application/gzip', 'Content-Disposition': 'attachment; filename="diablo-node.tgz"' });
  const tar = spawn('tar', ['-czf', '-', '-C', ROOT, '--exclude=node_modules', ...BUNDLE], { stdio: ['ignore', 'pipe', 'ignore'] });
  tar.on('error', () => { if (!res.headersSent) text(res, 500, 'tar is not available on the panel host\n'); else res.destroy(); });
  tar.stdout.pipe(res);
  res.on('close', () => tar.kill());
});

module.exports = router;
